### ISSUE TITLE
"Deep caching" only works in strict condition.

### ISSUE THREAD

**Issue by harrisyu** [imjp94/gd-shader-cache#1]
I just share some experience here :
Let's say you have preload some packed scenes in a script, following condition must be meet:
1. Use 'tool' keyword.
2. Use 'var' not 'const'.
3. Must be a static type var with ':PackedScene'.

**Comment by imjp94** [comment]
Thanks for sharing!

- [ ] 'tool' keyword is not required, it works on any script as long as the variable is exported
- [x] It only works on exported variable, for example: `export(PackedScene) var scene_ref`
- [x] Yes, it must be PackedScene variable. It is quite limiting at the moment, but it offers a simple workflow.

My bad for not elaborating more on exporting variable, will update the README to make it clearer.
